# Generated by Django 3.2.18 on 2023-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
