# Generated by Django 3.2.18 on 2023-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230617_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='Inactiv',
            field=models.CharField(default=1, max_length=100, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
