# Generated by Django 3.2.18 on 2023-06-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230618_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Inactiv',
        ),
    ]
