# Generated by Django 3.2.18 on 2023-06-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_card_inactiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('Inactive', 'Inactive')], max_length=20),
        ),
    ]
